language: ruby
env: CODECLIMATE_REPO_TOKEN=2deec4841978b14c5f8d2695508d4769837b5af8e585618235ab93295cd8321c RACK_ENV=development
rvm:
- 2.3.1
addons:
  code_climate:
    repo_token: 2deec4841978b14c5f8d2695508d4769837b5af8e585618235ab93295cd8321c
services:
- docker
before_install:
- docker pull ubuntu
- wget https://github.com/mumuki/mulang/releases/download/v0.2.8/mulang
- mv mulang bin/
- chmod +x bin/mulang
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: rubygems
  api_key:
    secure: OhFEVe4vNGbcWG9hndGew4Bfln2d6QhXINjcdF7Piur4dPLmfFNNrKLS6qEbirwXZMbSgGfjdyH+tq8yjc0rdjdvnlHxdRtqqKUGqqTZKmMLMWiLkUM+YUulSoUsAJjdDQRrCHdFJIDwrpnYD2IYuMkZtjY2xYSKgEQgCO452NY=
  gem: mumukit
  on:
    tags: true
    repo: mumuki/mumukit
